require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CarSearchesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # CarSearch. As you add validations to CarSearch, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CarSearchesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all car_searches as @car_searches" do
      car_search = CarSearch.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:car_searches)).to eq([car_search])
    end
  end

  describe "GET #show" do
    it "assigns the requested car_search as @car_search" do
      car_search = CarSearch.create! valid_attributes
      get :show, {:id => car_search.to_param}, valid_session
      expect(assigns(:car_search)).to eq(car_search)
    end
  end

  describe "GET #new" do
    it "assigns a new car_search as @car_search" do
      get :new, {}, valid_session
      expect(assigns(:car_search)).to be_a_new(CarSearch)
    end
  end

  describe "GET #edit" do
    it "assigns the requested car_search as @car_search" do
      car_search = CarSearch.create! valid_attributes
      get :edit, {:id => car_search.to_param}, valid_session
      expect(assigns(:car_search)).to eq(car_search)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new CarSearch" do
        expect {
          post :create, {:car_search => valid_attributes}, valid_session
        }.to change(CarSearch, :count).by(1)
      end

      it "assigns a newly created car_search as @car_search" do
        post :create, {:car_search => valid_attributes}, valid_session
        expect(assigns(:car_search)).to be_a(CarSearch)
        expect(assigns(:car_search)).to be_persisted
      end

      it "redirects to the created car_search" do
        post :create, {:car_search => valid_attributes}, valid_session
        expect(response).to redirect_to(CarSearch.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved car_search as @car_search" do
        post :create, {:car_search => invalid_attributes}, valid_session
        expect(assigns(:car_search)).to be_a_new(CarSearch)
      end

      it "re-renders the 'new' template" do
        post :create, {:car_search => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested car_search" do
        car_search = CarSearch.create! valid_attributes
        put :update, {:id => car_search.to_param, :car_search => new_attributes}, valid_session
        car_search.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested car_search as @car_search" do
        car_search = CarSearch.create! valid_attributes
        put :update, {:id => car_search.to_param, :car_search => valid_attributes}, valid_session
        expect(assigns(:car_search)).to eq(car_search)
      end

      it "redirects to the car_search" do
        car_search = CarSearch.create! valid_attributes
        put :update, {:id => car_search.to_param, :car_search => valid_attributes}, valid_session
        expect(response).to redirect_to(car_search)
      end
    end

    context "with invalid params" do
      it "assigns the car_search as @car_search" do
        car_search = CarSearch.create! valid_attributes
        put :update, {:id => car_search.to_param, :car_search => invalid_attributes}, valid_session
        expect(assigns(:car_search)).to eq(car_search)
      end

      it "re-renders the 'edit' template" do
        car_search = CarSearch.create! valid_attributes
        put :update, {:id => car_search.to_param, :car_search => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested car_search" do
      car_search = CarSearch.create! valid_attributes
      expect {
        delete :destroy, {:id => car_search.to_param}, valid_session
      }.to change(CarSearch, :count).by(-1)
    end

    it "redirects to the car_searches list" do
      car_search = CarSearch.create! valid_attributes
      delete :destroy, {:id => car_search.to_param}, valid_session
      expect(response).to redirect_to(car_searches_url)
    end
  end

end
